import type { GeoFeatureCollection, SavedPlace } from "@/lib/types";

const CONTINENT_NAMES = {
  africa: "Africa",
  antarctica: "Antarctica",
  asia: "Asia",
  europe: "Europe",
  northAmerica: "North America",
  oceania: "Oceania",
  southAmerica: "South America",
} as const;

const ISO2_TO_CONTINENT: Record<string, string> = {
  DZ: CONTINENT_NAMES.africa,
  AO: CONTINENT_NAMES.africa,
  BJ: CONTINENT_NAMES.africa,
  BW: CONTINENT_NAMES.africa,
  BF: CONTINENT_NAMES.africa,
  BI: CONTINENT_NAMES.africa,
  CM: CONTINENT_NAMES.africa,
  CV: CONTINENT_NAMES.africa,
  CF: CONTINENT_NAMES.africa,
  TD: CONTINENT_NAMES.africa,
  KM: CONTINENT_NAMES.africa,
  CD: CONTINENT_NAMES.africa,
  DJ: CONTINENT_NAMES.africa,
  EG: CONTINENT_NAMES.africa,
  GQ: CONTINENT_NAMES.africa,
  ER: CONTINENT_NAMES.africa,
  SZ: CONTINENT_NAMES.africa,
  ET: CONTINENT_NAMES.africa,
  GA: CONTINENT_NAMES.africa,
  GM: CONTINENT_NAMES.africa,
  GH: CONTINENT_NAMES.africa,
  GN: CONTINENT_NAMES.africa,
  GW: CONTINENT_NAMES.africa,
  CI: CONTINENT_NAMES.africa,
  KE: CONTINENT_NAMES.africa,
  LS: CONTINENT_NAMES.africa,
  LR: CONTINENT_NAMES.africa,
  LY: CONTINENT_NAMES.africa,
  MG: CONTINENT_NAMES.africa,
  MW: CONTINENT_NAMES.africa,
  ML: CONTINENT_NAMES.africa,
  MR: CONTINENT_NAMES.africa,
  MU: CONTINENT_NAMES.africa,
  MA: CONTINENT_NAMES.africa,
  MZ: CONTINENT_NAMES.africa,
  NA: CONTINENT_NAMES.africa,
  NE: CONTINENT_NAMES.africa,
  NG: CONTINENT_NAMES.africa,
  RW: CONTINENT_NAMES.africa,
  ST: CONTINENT_NAMES.africa,
  SN: CONTINENT_NAMES.africa,
  SC: CONTINENT_NAMES.africa,
  SL: CONTINENT_NAMES.africa,
  SO: CONTINENT_NAMES.africa,
  ZA: CONTINENT_NAMES.africa,
  SS: CONTINENT_NAMES.africa,
  SD: CONTINENT_NAMES.africa,
  TZ: CONTINENT_NAMES.africa,
  TG: CONTINENT_NAMES.africa,
  TN: CONTINENT_NAMES.africa,
  UG: CONTINENT_NAMES.africa,
  ZM: CONTINENT_NAMES.africa,
  ZW: CONTINENT_NAMES.africa,
  AQ: CONTINENT_NAMES.antarctica,
  AF: CONTINENT_NAMES.asia,
  AM: CONTINENT_NAMES.asia,
  AZ: CONTINENT_NAMES.asia,
  BH: CONTINENT_NAMES.asia,
  BD: CONTINENT_NAMES.asia,
  BT: CONTINENT_NAMES.asia,
  BN: CONTINENT_NAMES.asia,
  KH: CONTINENT_NAMES.asia,
  CN: CONTINENT_NAMES.asia,
  GE: CONTINENT_NAMES.asia,
  HK: CONTINENT_NAMES.asia,
  IN: CONTINENT_NAMES.asia,
  ID: CONTINENT_NAMES.asia,
  IR: CONTINENT_NAMES.asia,
  IQ: CONTINENT_NAMES.asia,
  IL: CONTINENT_NAMES.asia,
  JP: CONTINENT_NAMES.asia,
  JO: CONTINENT_NAMES.asia,
  KZ: CONTINENT_NAMES.asia,
  KW: CONTINENT_NAMES.asia,
  KG: CONTINENT_NAMES.asia,
  LA: CONTINENT_NAMES.asia,
  LB: CONTINENT_NAMES.asia,
  MO: CONTINENT_NAMES.asia,
  MY: CONTINENT_NAMES.asia,
  MV: CONTINENT_NAMES.asia,
  MN: CONTINENT_NAMES.asia,
  MM: CONTINENT_NAMES.asia,
  NP: CONTINENT_NAMES.asia,
  KP: CONTINENT_NAMES.asia,
  OM: CONTINENT_NAMES.asia,
  PK: CONTINENT_NAMES.asia,
  PH: CONTINENT_NAMES.asia,
  QA: CONTINENT_NAMES.asia,
  SA: CONTINENT_NAMES.asia,
  SG: CONTINENT_NAMES.asia,
  KR: CONTINENT_NAMES.asia,
  LK: CONTINENT_NAMES.asia,
  SY: CONTINENT_NAMES.asia,
  TW: CONTINENT_NAMES.asia,
  TJ: CONTINENT_NAMES.asia,
  TH: CONTINENT_NAMES.asia,
  TL: CONTINENT_NAMES.asia,
  TR: CONTINENT_NAMES.asia,
  TM: CONTINENT_NAMES.asia,
  AE: CONTINENT_NAMES.asia,
  UZ: CONTINENT_NAMES.asia,
  VN: CONTINENT_NAMES.asia,
  YE: CONTINENT_NAMES.asia,
  AL: CONTINENT_NAMES.europe,
  AD: CONTINENT_NAMES.europe,
  AT: CONTINENT_NAMES.europe,
  BY: CONTINENT_NAMES.europe,
  BE: CONTINENT_NAMES.europe,
  BA: CONTINENT_NAMES.europe,
  BG: CONTINENT_NAMES.europe,
  HR: CONTINENT_NAMES.europe,
  CY: CONTINENT_NAMES.europe,
  CZ: CONTINENT_NAMES.europe,
  DK: CONTINENT_NAMES.europe,
  EE: CONTINENT_NAMES.europe,
  FI: CONTINENT_NAMES.europe,
  FR: CONTINENT_NAMES.europe,
  DE: CONTINENT_NAMES.europe,
  GI: CONTINENT_NAMES.europe,
  GR: CONTINENT_NAMES.europe,
  HU: CONTINENT_NAMES.europe,
  IS: CONTINENT_NAMES.europe,
  IE: CONTINENT_NAMES.europe,
  IT: CONTINENT_NAMES.europe,
  XK: CONTINENT_NAMES.europe,
  LV: CONTINENT_NAMES.europe,
  LI: CONTINENT_NAMES.europe,
  LT: CONTINENT_NAMES.europe,
  LU: CONTINENT_NAMES.europe,
  MT: CONTINENT_NAMES.europe,
  MD: CONTINENT_NAMES.europe,
  MC: CONTINENT_NAMES.europe,
  ME: CONTINENT_NAMES.europe,
  NL: CONTINENT_NAMES.europe,
  MK: CONTINENT_NAMES.europe,
  NO: CONTINENT_NAMES.europe,
  PL: CONTINENT_NAMES.europe,
  PT: CONTINENT_NAMES.europe,
  RO: CONTINENT_NAMES.europe,
  RU: CONTINENT_NAMES.asia,
  SM: CONTINENT_NAMES.europe,
  RS: CONTINENT_NAMES.europe,
  SK: CONTINENT_NAMES.europe,
  SI: CONTINENT_NAMES.europe,
  ES: CONTINENT_NAMES.europe,
  SE: CONTINENT_NAMES.europe,
  CH: CONTINENT_NAMES.europe,
  UA: CONTINENT_NAMES.europe,
  GB: CONTINENT_NAMES.europe,
  VA: CONTINENT_NAMES.europe,
  AG: CONTINENT_NAMES.northAmerica,
  BS: CONTINENT_NAMES.northAmerica,
  BB: CONTINENT_NAMES.northAmerica,
  BZ: CONTINENT_NAMES.northAmerica,
  CA: CONTINENT_NAMES.northAmerica,
  CR: CONTINENT_NAMES.northAmerica,
  CU: CONTINENT_NAMES.northAmerica,
  DM: CONTINENT_NAMES.northAmerica,
  DO: CONTINENT_NAMES.northAmerica,
  SV: CONTINENT_NAMES.northAmerica,
  GD: CONTINENT_NAMES.northAmerica,
  GT: CONTINENT_NAMES.northAmerica,
  HT: CONTINENT_NAMES.northAmerica,
  HN: CONTINENT_NAMES.northAmerica,
  JM: CONTINENT_NAMES.northAmerica,
  MX: CONTINENT_NAMES.northAmerica,
  NI: CONTINENT_NAMES.northAmerica,
  PA: CONTINENT_NAMES.northAmerica,
  KN: CONTINENT_NAMES.northAmerica,
  LC: CONTINENT_NAMES.northAmerica,
  VC: CONTINENT_NAMES.northAmerica,
  TT: CONTINENT_NAMES.northAmerica,
  US: CONTINENT_NAMES.northAmerica,
  AU: CONTINENT_NAMES.oceania,
  FJ: CONTINENT_NAMES.oceania,
  KI: CONTINENT_NAMES.oceania,
  MH: CONTINENT_NAMES.oceania,
  FM: CONTINENT_NAMES.oceania,
  NR: CONTINENT_NAMES.oceania,
  NZ: CONTINENT_NAMES.oceania,
  PW: CONTINENT_NAMES.oceania,
  PG: CONTINENT_NAMES.oceania,
  WS: CONTINENT_NAMES.oceania,
  SB: CONTINENT_NAMES.oceania,
  TO: CONTINENT_NAMES.oceania,
  TV: CONTINENT_NAMES.oceania,
  VU: CONTINENT_NAMES.oceania,
  AR: CONTINENT_NAMES.southAmerica,
  BO: CONTINENT_NAMES.southAmerica,
  BR: CONTINENT_NAMES.southAmerica,
  CL: CONTINENT_NAMES.southAmerica,
  CO: CONTINENT_NAMES.southAmerica,
  EC: CONTINENT_NAMES.southAmerica,
  GY: CONTINENT_NAMES.southAmerica,
  PY: CONTINENT_NAMES.southAmerica,
  PE: CONTINENT_NAMES.southAmerica,
  SR: CONTINENT_NAMES.southAmerica,
  UY: CONTINENT_NAMES.southAmerica,
  VE: CONTINENT_NAMES.southAmerica,
};

const COUNTRY_NAME_TO_ISO2: Record<string, string> = {
  "united states": "US",
  "united states of america": "US",
  usa: "US",
  canada: "CA",
  mexico: "MX",
  brazil: "BR",
  argentina: "AR",
  colombia: "CO",
  peru: "PE",
  chile: "CL",
  uruguay: "UY",
  paraguay: "PY",
  bolivia: "BO",
  ecuador: "EC",
  venezuela: "VE",
  guyana: "GY",
  suriname: "SR",
  "united kingdom": "GB",
  uk: "GB",
  "great britain": "GB",
  england: "GB",
  scotland: "GB",
  wales: "GB",
  ireland: "IE",
  france: "FR",
  germany: "DE",
  italy: "IT",
  spain: "ES",
  portugal: "PT",
  netherlands: "NL",
  belgium: "BE",
  switzerland: "CH",
  austria: "AT",
  poland: "PL",
  czechia: "CZ",
  "czech republic": "CZ",
  slovakia: "SK",
  hungary: "HU",
  croatia: "HR",
  slovenia: "SI",
  greece: "GR",
  turkey: "TR",
  "türkiye": "TR",
  cyprus: "CY",
  iceland: "IS",
  norway: "NO",
  sweden: "SE",
  finland: "FI",
  denmark: "DK",
  estonia: "EE",
  latvia: "LV",
  lithuania: "LT",
  romania: "RO",
  bulgaria: "BG",
  serbia: "RS",
  bosnia: "BA",
  "bosnia and herzegovina": "BA",
  montenegro: "ME",
  albania: "AL",
  "north macedonia": "MK",
  ukraine: "UA",
  belarus: "BY",
  moldova: "MD",
  russia: "RU",
  georgia: "GE",
  armenia: "AM",
  azerbaijan: "AZ",
  morocco: "MA",
  egypt: "EG",
  tunisia: "TN",
  algeria: "DZ",
  libya: "LY",
  "south africa": "ZA",
  kenya: "KE",
  tanzania: "TZ",
  uganda: "UG",
  ghana: "GH",
  nigeria: "NG",
  ethiopia: "ET",
  rwanda: "RW",
  botswana: "BW",
  namibia: "NA",
  zambia: "ZM",
  zimbabwe: "ZW",
  senegal: "SN",
  "cote d'ivoire": "CI",
  "côte d’ivoire": "CI",
  "côte d'ivoire": "CI",
  india: "IN",
  pakistan: "PK",
  bangladesh: "BD",
  nepal: "NP",
  bhutan: "BT",
  "sri lanka": "LK",
  china: "CN",
  japan: "JP",
  "south korea": "KR",
  korea: "KR",
  "north korea": "KP",
  mongolia: "MN",
  taiwan: "TW",
  "hong kong": "HK",
  thailand: "TH",
  vietnam: "VN",
  cambodia: "KH",
  laos: "LA",
  myanmar: "MM",
  malaysia: "MY",
  singapore: "SG",
  indonesia: "ID",
  philippines: "PH",
  brunei: "BN",
  "timor leste": "TL",
  "timor-leste": "TL",
  kazakhstan: "KZ",
  uzbekistan: "UZ",
  kyrgyzstan: "KG",
  tajikistan: "TJ",
  turkmenistan: "TM",
  afghanistan: "AF",
  iran: "IR",
  iraq: "IQ",
  israel: "IL",
  jordan: "JO",
  lebanon: "LB",
  "saudi arabia": "SA",
  "united arab emirates": "AE",
  qatar: "QA",
  bahrain: "BH",
  kuwait: "KW",
  oman: "OM",
  yemen: "YE",
  australia: "AU",
  "new zealand": "NZ",
  fiji: "FJ",
  papua: "PG",
  "papua new guinea": "PG",
};

const CONTINENT_BOUNDS: Record<string, [[number, number], [number, number]]> = {
  Africa: [
    [-35, -19],
    [38, 53],
  ],
  Antarctica: [
    [-90, -180],
    [-58, 180],
  ],
  Asia: [
    [-10, 25],
    [82, 180],
  ],
  Europe: [
    [34, -31],
    [72, 60],
  ],
  "North America": [
    [7, -170],
    [84, -52],
  ],
  Oceania: [
    [-50, 110],
    [25, 180],
  ],
  "South America": [
    [-56, -92],
    [13, -34],
  ],
};

function normalizeCountry(value: string) {
  return value.trim().toLowerCase();
}

export function getContinentFromCountryCode(countryCode: string | null | undefined) {
  if (!countryCode) return null;
  const normalizedCode = countryCode.trim().toUpperCase();
  return ISO2_TO_CONTINENT[normalizedCode] ?? null;
}

export function getCountryCodeFromCountryName(country: string | null | undefined) {
  if (!country) return null;
  return COUNTRY_NAME_TO_ISO2[normalizeCountry(country)] ?? null;
}

export function getContinentFromCountryName(country: string | null | undefined) {
  const code = getCountryCodeFromCountryName(country);
  return getContinentFromCountryCode(code);
}

export function resolveContinentForPlace(place: Pick<SavedPlace, "continent" | "country">) {
  return place.continent ?? getContinentFromCountryName(place.country);
}

export function getContinentFeatureCollection(
  continent: string | null | undefined
): GeoFeatureCollection | null {
  if (!continent) return null;
  const bounds = CONTINENT_BOUNDS[continent];

  if (!bounds) return null;

  const [[south, west], [north, east]] = bounds;

  return {
    type: "FeatureCollection",
    features: [
      {
        type: "Feature",
        properties: { name: continent },
        geometry: {
          type: "Polygon",
          coordinates: [
            [
              [west, south],
              [east, south],
              [east, north],
              [west, north],
              [west, south],
            ],
          ],
        },
      },
    ],
  };
}
